language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-rulez==1.0.1 --use-mirrors
  - pip install -q coveralls --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - coverage run --source=rottweiler tests/testapp/manage.py test rottweiler
after_success:
  - coveralls
notifications:
  hipchat:
    rooms:
      secure: "nC3jkmUXAffoVoQ4Vm1tuVr6IADYPIbG3V6d/5+6MxsATqzO1DbSjbZ5Gr/NVuD2GksBItah/8CjAWFl3OvEqsoy+Bs/uuq/xQLH66pyulUAMc2jN+Gkgdsgzp5utBCmB2WmNU/a/t2YDNaRu1yvWO5l2x7hFYZ+dvPVueQU7mg="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: change
  on_failure: always
