language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-rulez==1.0.1 --use-mirrors
  - pip install -q coveralls --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - coverage run --source=rottweiler tests/testapp/manage.py test rottweiler
notifications:
  hipchat:
    rooms:
      secure: "Bv/nYpAsoSr4kQC9vXixdOEcU5rwza551hEHOrnCEj/dU5cvuSkbyQIVW4SKBkidVHmS/OQjKhxhpniuw7GTzfGCe2cBj1MsyLy4TFs9FEIE0vWhj0w/ZtkSvHIdAoP94qRr13CT2kSM7MLj/DzjET0GBpeltWly4KdiTo3okGY="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: change
  on_failure: always
